<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'agent' => 0,
                'avatar' => NULL,
                'company_id' => NULL,
                'contact_name' => 'Admin User',
                'created_at' => '2022-04-04 04:23:20',
                'current_team_id' => NULL,
                'deleted_at' => NULL,
                'department' => NULL,
                'email' => 'admin@regeinecareer.com',
                'email_verified_at' => NULL,
                'employer' => 0,
                'id' => 1,
                'last_login' => NULL,
                'name' => 'Admin',
                'password' => '$2y$10$v4v0OhNHNrBYgMbOok3JBOV4p2AQCGaQgmAoCE8SY0P75HtiWrDWq',
                'phone' => NULL,
                'position' => NULL,
                'preferences' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => 'R1t5uJyTPxBBS4PTslFBAILEROgcQovhtyQSKtb7VpFr6Jqg6Lt7cVBqEOY0',
                'super' => 1,
                'surname' => 'User',
                'two_factor_confirmed_at' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2022-04-06 00:02:50',
            ),
            1 => 
            array (
                'agent' => 1,
                'avatar' => NULL,
                'company_id' => NULL,
                'contact_name' => 'Agent User',
                'created_at' => '2022-04-04 04:23:33',
                'current_team_id' => NULL,
                'deleted_at' => NULL,
                'department' => NULL,
                'email' => 'agent@regeinecareer.com',
                'email_verified_at' => NULL,
                'employer' => 0,
                'id' => 2,
                'last_login' => NULL,
                'name' => 'Agent',
                'password' => '$2y$10$qOcwpzagaC41jXR6f/hloef2Z7Es3q6jrPsYii05pj9BrIBtXOTNy',
                'phone' => NULL,
                'position' => NULL,
                'preferences' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'super' => 0,
                'surname' => 'User',
                'two_factor_confirmed_at' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2022-04-06 00:03:00',
            ),
            2 => 
            array (
                'agent' => 0,
                'avatar' => NULL,
                'company_id' => NULL,
                'contact_name' => 'Employer User',
                'created_at' => '2022-04-04 04:23:42',
                'current_team_id' => NULL,
                'deleted_at' => NULL,
                'department' => NULL,
                'email' => 'employer@regeinecareer.com',
                'email_verified_at' => NULL,
                'employer' => 1,
                'id' => 3,
                'last_login' => NULL,
                'name' => 'Employer',
                'password' => '$2y$10$KvzTzrus.VSAcmfQC18r2OsvXMN5cd7KXPPMw45oPsmWrqgKHKjdC',
                'phone' => NULL,
                'position' => NULL,
                'preferences' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => '0QZqMRJTUkj4MFLiCHssI3sNlcj8oL7AG1OhGeWMFWDvAEMJq8KsDDPSGIud',
                'super' => 0,
                'surname' => 'User',
                'two_factor_confirmed_at' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2022-04-06 00:03:13',
            ),
            3 => 
            array (
                'agent' => 0,
                'avatar' => NULL,
                'company_id' => NULL,
                'contact_name' => 'Guest User',
                'created_at' => '2022-04-04 05:23:07',
                'current_team_id' => NULL,
                'deleted_at' => NULL,
                'department' => NULL,
                'email' => 'guest@regeinecareer.com',
                'email_verified_at' => NULL,
                'employer' => 0,
                'id' => 4,
                'last_login' => NULL,
                'name' => 'Guest',
                'password' => '$2y$10$nSFiMILDdjNicqcrwUI.YeoHyyZcfcEmuCrE2l5WJ0Uj3rm5kY1Z.',
                'phone' => NULL,
                'position' => NULL,
                'preferences' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'super' => 0,
                'surname' => 'User',
                'two_factor_confirmed_at' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2022-04-04 05:23:07',
            ),
            4 => 
            array (
                'agent' => 0,
                'avatar' => NULL,
                'company_id' => 1,
                'contact_name' => 'Bella Xu',
                'created_at' => '2022-04-06 00:07:07',
                'current_team_id' => NULL,
                'deleted_at' => NULL,
                'department' => NULL,
                'email' => 'bella@regeinecareer.com',
                'email_verified_at' => NULL,
                'employer' => 1,
                'id' => 5,
                'last_login' => NULL,
                'name' => 'Bella',
                'password' => '$2y$10$RyVfuN6j1Te5Ki0juGwJneBUKlAWBsuVPkCnWd4iuRPVEVD69InTe',
                'phone' => NULL,
                'position' => NULL,
                'preferences' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'super' => 0,
                'surname' => 'Xu',
                'two_factor_confirmed_at' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2022-04-06 00:11:19',
            ),
            5 => 
            array (
                'agent' => 1,
                'avatar' => NULL,
                'company_id' => 1,
                'contact_name' => 'Maya Jazbani',
                'created_at' => '2022-04-06 00:07:50',
                'current_team_id' => NULL,
                'deleted_at' => NULL,
                'department' => NULL,
                'email' => 'maya@regeinecareer.com',
                'email_verified_at' => NULL,
                'employer' => 0,
                'id' => 6,
                'last_login' => NULL,
                'name' => 'Maya',
                'password' => '$2y$10$DezAG4BgQnab/VTW6N67J.vU0IOCN7zrnKx9rZpv2uPBYKcAOw/a6',
                'phone' => NULL,
                'position' => NULL,
                'preferences' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'super' => 0,
                'surname' => 'Jazbani',
                'two_factor_confirmed_at' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2022-04-06 00:11:31',
            ),
            6 => 
            array (
                'agent' => 0,
                'avatar' => NULL,
                'company_id' => 2,
                'contact_name' => 'Jonny Zhu',
                'created_at' => '2022-04-06 00:08:50',
                'current_team_id' => NULL,
                'deleted_at' => NULL,
                'department' => NULL,
                'email' => 'jonny@regeinecareer.com',
                'email_verified_at' => NULL,
                'employer' => 1,
                'id' => 7,
                'last_login' => NULL,
                'name' => 'Jonny',
                'password' => '$2y$10$sCzP9H5E5kSHTJY4PeQ6OekTFJw5Ohg8iFOiLWOkBzoxl0cb3FbP6',
                'phone' => NULL,
                'position' => NULL,
                'preferences' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'super' => 0,
                'surname' => 'Zhu',
                'two_factor_confirmed_at' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2022-04-06 00:11:38',
            ),
            7 => 
            array (
                'agent' => 1,
                'avatar' => NULL,
                'company_id' => 2,
                'contact_name' => 'Eric Zhou',
                'created_at' => '2022-04-06 00:09:14',
                'current_team_id' => NULL,
                'deleted_at' => NULL,
                'department' => NULL,
                'email' => 'eric@regeinecareer.com',
                'email_verified_at' => NULL,
                'employer' => 0,
                'id' => 8,
                'last_login' => NULL,
                'name' => 'Eric',
                'password' => '$2y$10$dj/QLq23cyerMfU/WB6gFu7x/WLcndzNd9rkjsAQwVojD.Ul.BbpK',
                'phone' => NULL,
                'position' => NULL,
                'preferences' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'super' => 0,
                'surname' => 'Zhou',
                'two_factor_confirmed_at' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2022-04-06 00:11:46',
            ),
            8 => 
            array (
                'agent' => 0,
                'avatar' => NULL,
                'company_id' => 2,
                'contact_name' => 'Kevin Lim',
                'created_at' => '2022-04-06 00:10:05',
                'current_team_id' => NULL,
                'deleted_at' => NULL,
                'department' => NULL,
                'email' => 'kevin@regeinecareer.com',
                'email_verified_at' => NULL,
                'employer' => 0,
                'id' => 9,
                'last_login' => NULL,
                'name' => 'Kevin',
                'password' => NULL,
                'phone' => NULL,
                'position' => NULL,
                'preferences' => NULL,
                'profile_photo_path' => NULL,
                'remember_token' => NULL,
                'super' => 0,
                'surname' => 'Lim',
                'two_factor_confirmed_at' => NULL,
                'two_factor_recovery_codes' => NULL,
                'two_factor_secret' => NULL,
                'updated_at' => '2022-04-06 00:11:54',
            ),
        ));
        
        
    }
}